#+TITLE:     The management of databases for a large organisation
#+AUTHOR:    James Hurford
#+EMAIL:     
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  en
#+OPTIONS:   H:3 num:t toc:t \n:nil @:t ::t |:t ^:t -:t f:t *:t <:t
#+OPTIONS:   TeX:t LaTeX:t skip:nil d:nil todo:t pri:nil tags:not-in-toc
#+INFOJS_OPT: view:nil toc:nil ltoc:t mouse:underline buttons:0 path:http://orgmode.org/org-info.js
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LINK_UP:   
#+LINK_HOME: 
#+XSLT: 

* Introduction


* Workload
** The Problem
Workload is a measure of how many virtual hours each staff member is
going to be doing for the coming year. The purpose of Workload is to
spread the workload as fairly among the staff.  It is a artificial
measurement, using a formula to determine a individuals hour based on
a set of predetermined metrics.

The task is to create a application to take in:

+ For each paper offered

  + For each person teaching this paper how much of the paper they
    are teaching.
  + who the global coordinator is
  + who the local coordinator is

+ The Admin roles for each of the members of staff and how much
  the admin roles are worth in Workload hours.
+ For each staff
  + Which postgraduate they are supervising
    + how much supervision in percentage terms they are giving
    + Given that each postgraduate degree is worth different hours
      + What percentage of supervision they give and thus how many of
        those hours do they get.

This process gets it's information from 2 databases.  One being the
postgraduate database, and the other a local custom built MySQL
database.  All the information needed is stored on the local MySQL
database, with 


It could also be used as a tool to indicate where resources are needed
the most, if a extra staff member is needed.


*** What it is that this application is replacing
Currently a Excel spreadsheet is being used to store the input data
and calculate and display the results.  The current solutions is to
complex and needs a easier method for inputting the data.  The amount
of data inputted is coming near to the limit of how much Excel can
take.

Currently cluster leaders put together the workload hour report for
their cluster.  They then pass that information onto Glenda who then
inputs the data into a spreadsheet application.  Micheal also compiles
a report of the postgraduate hours for each staff member and sends
this to Glenda who also puts this into the spreadsheet application.
The entire process is time consuming and error prone, and mistakes
can take a long time to be fixed.

*** How can a application be more flexible than the spreadsheet solution
What do we mean by flexible?  What form can this take and why should
we do this?

For SEAT Management to more efficiently do their job they would
benefit from a application which streamlines the data input process
and minimises the amount of intervention that is needed to produce the
required reports.  I planned to remove a few steps from this process.


*** How to represent it to users?
What form will this take?  What sort of format will be used?
** Challenges
*** What question do you ask first?
*** What methods of development do I use?
Is there one which suits a individual best?  How does one keep
themselves motivated?  Do you use a version control system?  What
system and does it matter?


Produced a prototype of the application in html, css and javascript.
Was not the optimal choice, but it demonstrated my initial ideas.  I
then took this prototype and showed it to Glenda, Stephen and Hans,
who approved of it.  I then went ahead and implemented it in python,
using the django framework, along with some javascript, and css styling.
*** What programming platform do I use?
What language and does it matter?  Which works best for the scenario I
choose?  Is a compiled system a good choice?
*** Where is it going to be deployed?
This is important, as it decides what options are available to you and
poses its own challenges.
*** Security
How important is security, and how doe you overcome these problems?

Security seems to be a concern.  The only ones who should be able to
access the data produced by this application are academic staff, and managers
and cluster leaders. The Workload of other academic staff, should be
visible to each other.  Academic staff should only be able to view
data, and alter their personal information, but not anything else.
Cluster leaders should be able to alter 
*** How to represent it to users
What do users respond best to and do you want to force them to install
a programme on their computer or have it available anywhere on the intranet?
*** Where do I get my data from and how do I store it
What other technologies to I have to interact with and how can I
minimise this interaction?
*** What functionality do I implement
How flexible do you want it?  What does it need to do and what extra
features can you justify adding to it

jquery hover events work well in changing a html tag into a html form
tag, like a <span> into a <input type="text".../>, and back again, but
this doesn't work so well when going back to a span from a
<select../>.  If you bring up the drop down menu and try and use the
mouse to select one of the options, the hover out event wound trigger
changing the element back to a <span> tag.  This is not what is
wanted, so the hover out event has to disabled when the <select> is
clicked with the change back event being tied to the change event
associated with <select>.  The problem with this is that if the user
doesn't change the selection the change event is not triggered so the
<select> control stays where it is.  This is not wanted, so but there
is nothing that can be done simply to overcome this.  The decision was
to use the focus events, so that when the user select another thing in
the page, the tag changes back to the span tag.  This is not ideal,
but it's these kind of compromises that have to be dealt with when
creating web applications like this, that rely on only w3c standards
compliant html, css and javascript.

The biggest barrier to what I can do is what do all the browsers have
in common.  What css standards do they all implement?  What html tags
will they all use, and what javascript functionality do they all
implement?  That is the biggest problem when doing a web application,
the fact that each browser behaves in a different way in the way they
display your pages, and the javascript implementation will have
different behaviors, like IE is pedantic about have variable declared
with the var tag.

*** Responsiveness of application
How do you overcome the problem of doing lots of IO and calculations
at once?  How fast does it have to be and how can you optimise it.

There are two places to process the data and one place to display the
results. You can use client side scripts, like javascript to process
the data, and it can be processed on the server side.  The more data
that is processed on the server side the less people that it can
handle at once.  Also doing it all on the server side means the pages
have to be reloaded every time a new choice is made.  The client side
processing of data, takes some of the load off the server, but it has
the downside, of relying on the clients browser to have the
functionality required, like javascript, which could be of a different
version to the one that the site was developed for.  Also javascript
seems to be a lot slower to process data than the server side scripts
are.  The goal here is to have the pages reloaded as little as
possible, but load up in a reasonable time.  How much time is
reasonable depends on who you talk to, but I feel that more than 30
seconds is not acceptable.  Fortunately there is a javascript library,
present in all major browsers, called Ajax.  It can be used to fetch
information from the server without reloading the page.  I also found
that using libraries like jquery, overcome most of the
incompatibilities of javascript between browsers, and also have some
convenient routines to make finding and manipulating the displayed
page through the HTML DOM.  It also handles events like clicking of
tags, like clicking a <div> element, making it easier to control the
way it looks and responds to the users input.  The combination of
javascript and ajax, makes the creation of web based applications
possible.  The addition of jquery, makes manipulation of elements
easier.  (must provide proof)

jquery makes for a uniform javascript api across most of the major
browsers, like IE and Firefox.  This simplifies the development of web
applications and reduces the number of issues that come from having
more than one brand of web browser accessing the site.


I at first used javascript to fill the table entries.  This worked,
but it was extremely slow.  I decided this was not acceptable, as
users expect a quick response to queries, so I implemented it on the
server side.  It was still slow, but faster than the javascript
version.  (Diagrams needed of both systems used)

#+BEGIN_DITAA client-side -r -S -E
+----------+
| Workload |
| Stats    |
| {d}      | 
| cC02     |
+-----+----+  
      ^
      |
+-----+------+
| {io}       |
| Javascript |
| cBLU       |
+-----+------+
      ^
      |
+-----+------+
| {io}       |
| django     |
| cBLU       |
+-----+------+
      ^
      |
+------------+
| {s}        |
| DB         |
| c888       |
+------------+

#+END_DITAA

** Solutions
*** Method of development
Web based application developed in python using the django framework.
Needs to be able to run in a web server environment.  Apache is being
used, with the module wsgi. mod_python could also be used, but
development and support for mod_python doesn't exist anymore, and wsgi
is recommended anyway.
*** Deploying the application
Theoretically it could be deployed on any OS which has a web server
that can run python. However it was decided to run it on a Centos
Server under the SEAT domain.
*** Security
While it is an issue is not a high priority.  We have been
given the impression that the staff in SEAT are open about the hours
they have done, and honest.  The restriction I imposed are those of
write access.  Administrators get access to everything, Staff get to
only view the results, and cluster leaders get to only alter the parts
that are relevant to their cluster.
*** Framework choice
Django was chosen, as it is a python library, and we wanted to solve
this problem in python.  The django framework is a kitchen sink
approach, for web development with a model (show model diagram).

*** Database and importing of data
*** Feature choice
*** Code optimisation
** Conclusion

* Paper Planner
** The Problem
*** How to represent it to users
*** How to solve it
** Solutions chosen
*** Web Representation
*** Constraints Satisfaction
*** Database use.
*** Programming library choice
*** Programming language choice
** Challenges
*** Using python to run C++ code
Python can import C libraries using ctypes and run C functions.
*** How to represent and encode the problem
** Conclusion
Conclusion is here
